### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by mingfang** [mikub/titanoboa#13]
I see there's an image here https://hub.docker.com/layers/titanoboa/titanoboa/0.9.0/images/sha256-367dac2bcc85717872a06646c0605a9ff339663d8b92ced748f9322b3be6b600?context=explore

but where's the Dockerfile?

**Comment by mikub** [comment]
Hi @mingfang,
I added a sample docker file I am using for creating an image for each release. It is just a basic setup, without any database or an underlying mq provider, but it should still do.

Cheers
Miro

**Comment by mingfang** [comment]
That's great. Thanks.
